title: Optimistic Industries
baseurl: ""
url: "https://optimistic.industries"

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page