title: Optimistic Industries
baseurl: "/<optimistic-industries>"
url: "https://<connor-rose>.github.io"

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page